perl /var/scripts/perl/Discovery7.pl dbin=10,10 dbout pwd=ctipublic con=0 email=ok &>/var/log/scripts/discovery/Discovery7-10.out &
perl /var/scripts/perl/Discovery7.pl dbin=9,10 dbout pwd=ctipublic con=0 email=ok &>/var/log/scripts/discovery/Discovery7-9.out &
perl /var/scripts/perl/Discovery7.pl dbin=8,10 dbout pwd=ctipublic con=0 email=ok &>/var/log/scripts/discovery/Discovery7-8.out &
perl /var/scripts/perl/Discovery7.pl dbin=7,10 dbout pwd=ctipublic con=0 email=ok &>/var/log/scripts/discovery/Discovery7-7.out &
perl /var/scripts/perl/Discovery7.pl dbin=6,10 dbout pwd=ctipublic con=0 email=ok &>/var/log/scripts/discovery/Discovery7-6.out &
perl /var/scripts/perl/Discovery7.pl dbin=5,10 dbout pwd=ctipublic con=0 email=ok &>/var/log/scripts/discovery/Discovery7-5.out &
perl /var/scripts/perl/Discovery7.pl dbin=4,10 dbout pwd=ctipublic con=0 email=ok &>/var/log/scripts/discovery/Discovery7-4.out &
perl /var/scripts/perl/Discovery7.pl dbin=3,10 dbout pwd=ctipublic con=0 email=ok &>/var/log/scripts/discovery/Discovery7-3.out &
perl /var/scripts/perl/Discovery7.pl dbin=2,10 dbout pwd=ctipublic con=0 email=ok &>/var/log/scripts/discovery/Discovery7-2.out &
perl /var/scripts/perl/Discovery7.pl dbin=1,10 dbout pwd=ctipublic con=0 email=ok &>/var/log/scripts/discovery/Discovery7-1.out &